name: quiz_commercial2024
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+49

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.0
  easy_localization: ^3.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  firebase_storage: ^12.3.7
  auto_size_text: ^3.0.0
  share_plus: ^11.0.0
  lottie: ^3.2.0
  video_player: ^2.9.2
  permission_handler: ^12.0.0+1
  flutter_sound: ^9.17.0
  firebase_messaging: ^15.2.7
  flutter_html: ^3.0.0-beta.2
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  just_audio: ^0.9.42
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  audio_session: ^0.1.23
  collection: ^1.18.0
  shared_preferences: ^2.3.5
  audioplayers: ^6.4.0
  record: ^6.0.0
  flutter_local_notifications: ^19.2.1
  circle_list: ^1.0.5
  google_mobile_ads: ^5.3.1
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.3
  http_parser: ^4.0.2
  flutter_dotenv: ^5.2.1
  flutter_staggered_animations: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/correct.mp3
    - assets/sounds/incorrect.mp3
    - assets/icons/Google.svg
    - assets/images/logo.png
    - assets/images/system.png
    - assets/images/user.png
    - assets/videos/video_for_80.mp4
    - assets/videos/video_for_90.mp4
    - assets/videos/video_for_100.mp4
    - assets/Animation_quiz.json
    - assets/animation_book1.json
    - assets/Animation_salesstat.json
    - assets/Animation_gagner.json
    - assets/videos/video_for_perdu.mp4
    - assets/images/background_concours.png
    - assets/images/france.png
    - assets/translations/fr.json
    - assets/images/united-kingdom.png
    - assets/translations/en.json
    - assets/images/rgpd.jpeg
    - assets/parler.json
    - assets/ici.json
    - assets/images/backgroundlogin.jpg
    - assets/animations/level_up.json
    - assets/images/sam.top.png
    - assets/default_user.png
    - assets/images/mode en ligne.png
    - assets/Animation 1.json
    - assets/Animation 2.json
    - assets/Animation 3.json
    - assets/Animation continue.json
    - assets/animations/salle de defi.json
    - .env
    - assets/scripts/immobilier.json
    - assets/scripts/porte_a_porte.json
    - assets/scripts/teleconseillers.json
    - assets/scripts/gms.json
    - assets/scripts/services_premium.json
    - assets/scripts/grand_compte.json        # â† nouveau
    - assets/scripts/script_standard.json

